api_platform:
  mapping:
    paths: ['%kernel.project_dir%/src/Entity']
  graphql:
    enabled: true
    graphql_playground:
      enabled: true
  formats:
    jsonld: ['application/ld+json']
    json: ['application/json']
