doctrine:
    dbal:
        default_connection: data
        connections:
            data:
                url: '%env(PG_DSN)%'
                driver: 'pdo_pgsql'
                server_version: '16'
                mapping_types:
                    ltree: string
            infra:
                url: '%env(MYSQL_DSN)%'
                driver: 'pdo_mysql'
                server_version: '8.0'
    orm:
        default_entity_manager: data
        entity_managers:
            data:
                connection: data
                naming_strategy: doctrine.orm.naming_strategy.default
                mappings:
                    App:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
            infra:
                connection: infra
                naming_strategy: doctrine.orm.naming_strategy.default
                mappings:
                    AppInfra:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Projection'
                        prefix: 'App\Projection'
                        alias: AppInfra
