services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Cataloging\Infrastructure\HttpWebhookSender:
        arguments: [ '@http_client', '%env(CATEGORY_WEBHOOK_ENDPOINT)%' ]
    App\Cataloging\Infrastructure\MessengerOutboxDispatcher: ~
    App\Cataloging\Infrastructure\CacheInvalidator: ~
