security:
  access_decision_manager:
    strategy: unanimous
  role_hierarchy:
    ROLE_ADMIN: [ROLE_USER]
    ROLE_MERCHANT: [ROLE_USER]

framework:
  response_listener: { enabled: true }
category:
  security:
    csp: "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'"
    frame_options: 'DENY'
