security:
  firewalls:
    category_api:
      pattern: ^/api/category
      lazy: true
      stateless: true
      provider: category_jwt
  providers:
    category_jwt:
      id: App\Security\JwtUserProvider
  access_control:
    - { path: ^/api/category/tree, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/category/.+/move, roles: IS_AUTHENTICATED_FULLY }
