api_platform:
  mapping:
    paths: ['%kernel.project_dir%/src/Entity']
  graphql:
    enabled: false
    graphql_playground:
      enabled: false
  formats:
    jsonld: ['application/ld+json']
    json: ['application/json']
