services:
    App\Cataloging\Infrastructure\ProductWebhookPublisher:
        arguments: [ '@http_client', '%env(PRODUCT_WEBHOOK_URL)%' ]
    App\Cataloging\Infrastructure\OrderWebhookPublisher:
        arguments: [ '@http_client', '%env(ORDER_WEBHOOK_URL)%' ]
