security:
    firewalls:
        category_api:
            pattern: ^/api/catalog/category
            lazy: true
            stateless: true
            provider: category_jwt
    providers:
        category_jwt:
            id: App\Cataloging\UserProvider\JwtUserProvider
