security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    access_decision_manager:
        strategy: unanimous
        allow_if_all_abstain: false
        allow_if_equal_granted_denied: false
    erase_credentials: true
    # Example simple role hierarchy
    role_hierarchy:
        ROLE_CATEGORY_OWNER: [ ROLE_CATEGORY_EDITOR, ROLE_CATEGORY_RULE, ROLE_CATEGORY_MERCH ]
        ROLE_CATEGORY_EDITOR: [ ROLE_CATEGORY_RULE, ROLE_CATEGORY_MERCH ]
