services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\Infrastructure\HttpWebhookSender:
    arguments: ['@http_client', '%env(CATEGORY_WEBHOOK_ENDPOINT)%']
  App\Infrastructure\MessengerOutboxDispatcher: ~
  App\Infrastructure\CacheInvalidator: ~
