services:
  App\Infra\Category\ProductWebhookPublisher:
    arguments: ['@http_client', '%env(PRODUCT_WEBHOOK_URL)%']
  App\Infra\Category\OrderWebhookPublisher:
    arguments: ['@http_client', '%env(ORDER_WEBHOOK_URL)%']
