framework:
  messenger:
    transports:
      async_low: '%env(RABBITMQ_DSN)%/category?queues[category_low]=1'
      async_high: '%env(RABBITMQ_DSN)%/category?queues[category_high]=1'
      sync: 'sync://'
    routing:
      'App\Message\RecomputeVirtualtestsMessage': async_high
