security:
  firewalls:
    category_api:
      pattern: ^/api/category
      stateless: true
      provider: category_jwt
      jwt: ~
  providers:
    category_jwt:
      id: App\Security\Category\JwtUserProvider
  access_control:
    - { path: ^/api/category/tree, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/category/.+/move, roles: ROLE_ADMIN }
