category_doc_ui:
  path: /api/doc
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    path: '/doc/swagger/'
    permanent: false

category_doc_spec:
  path: /api/doc/openapi.yaml
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    path: '/doc/swagger/category-openapi.yaml'
    permanent: false
