app.swagger_ui:
    path: /api/catalog/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
    path: /api/catalog/doc/json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }
