<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Evacuate legacy alias storage into canonical category slug history storage.
 *
 * @noinspection PhpClassNamingConventionInspection
 */
final class Version20251102093000_category_slug_history_evacuation extends AbstractMigration
{
    /** @noinspection PhpMissingParentCallCommonInspection */
    public function getDescription(): string
    {
        return 'Rename category_alias storage into category_slug_history and canonicalize slug column naming';
    }

    /** @noinspection PhpMissingParentCallCommonInspection */
    public function up(Schema $schema): void
    {
        $schemaManager = $this->connection->createSchemaManager();
        $platform = $this->connection->getDatabasePlatform()->getName();
        $tables = array_map('strtolower', $schemaManager->listTableNames());
        $hasAlias = in_array('category_alias', $tables, true);
        $hasHistory = in_array('category_slug_history', $tables, true);

        if (!$hasAlias && !$hasHistory) {
            if ('postgresql' === $platform) {
                $this->addSql('CREATE TABLE category_slug_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(180) NOT NULL, category_id VARCHAR(26) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
            } else {
                $this->addSql('CREATE TABLE category_slug_history (id INT AUTO_INCREMENT NOT NULL, slug VARCHAR(180) NOT NULL, category_id VARCHAR(26) NOT NULL, created_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            }
            $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_category_slug_history_slug ON category_slug_history(slug)');

            return;
        }

        if ($hasAlias && !$hasHistory) {
            $this->addSql('ALTER TABLE category_alias RENAME TO category_slug_history');
        }

        $columns = array_change_key_case($schemaManager->listTableColumns($hasHistory ? 'category_slug_history' : 'category_alias'));
        if (isset($columns['old_slug']) && !isset($columns['slug'])) {
            if ('postgresql' === $platform) {
                $this->addSql('ALTER TABLE category_slug_history RENAME COLUMN old_slug TO slug');
            } else {
                $this->addSql('ALTER TABLE category_slug_history CHANGE old_slug slug VARCHAR(180) NOT NULL');
            }
        }

        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_category_slug_history_slug ON category_slug_history(slug)');
    }

    /** @noinspection PhpMissingParentCallCommonInspection */
    public function down(Schema $schema): void
    {
        $schemaManager = $this->connection->createSchemaManager();
        if (!$schemaManager->tablesExist(['category_slug_history'])) {
            return;
        }

        $platform = $this->connection->getDatabasePlatform()->getName();
        $columns = array_change_key_case($schemaManager->listTableColumns('category_slug_history'));
        if (isset($columns['slug']) && !isset($columns['old_slug'])) {
            if ('postgresql' === $platform) {
                $this->addSql('ALTER TABLE category_slug_history RENAME COLUMN slug TO old_slug');
            } else {
                $this->addSql('ALTER TABLE category_slug_history CHANGE slug old_slug VARCHAR(180) NOT NULL');
            }
        }

        $this->addSql('ALTER TABLE category_slug_history RENAME TO category_alias');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_category_alias ON category_alias(old_slug)');
    }
}
