version: '3.9'
services:
  app:
    build: ./
    ports:
      - '8080:8080'
    depends_on:
      - pg
      - mysql
  pg:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: category
      POSTGRES_USER: category
      POSTGRES_DB: category
    volumes:
      - ./tools/docker/init-pg-ltree.sql:/docker-entrypoint-initdb.d/10-init-ltree.sql
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: category
      MYSQL_DATABASE: category
