services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Controller\StatusHandler:
    tags: ['controller.service_arguments']

  App\Controller\CategoryListHandler:
    tags: ['controller.service_arguments']

  App\Controller\CollectionListHandler:
    tags: ['controller.service_arguments']

  App\Controller\CategoryAttachmentController:
    tags: ['controller.service_arguments']

  App\Repository\CatalogAttachmentRepository: ~
  App\RepositoryInterface\CatalogAttachmentRepositoryInterface: '@App\Repository\CatalogAttachmentRepository'

  App\Security\:
    resource: '../src/Security/'
