services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Cataloging\Service\CatalogGraphqlResolverService: ~
    App\Cataloging\Service\CatalogGraphqlFacetResolverService: ~
    App\Cataloging\Service\Category\Graphql\CategoryGraphqlGuard: ~
    App\Cataloging\Service\Category\Graphql\CategoryLoader: ~
