apiVersion: apps/v1
kind: Deployment
metadata:
    name: category
spec:
    replicas: 1
    selector:
        matchLabels:
            app: category
    template:
        metadata:
            labels:
                app: category
        spec:
            containers:
                -   name: category
                    image: { { .Values.image.repository } }:{{ .Values.image.tag }}
                    ports:
                          - containerPort: { { .Values.service.port } }
