Category:
  type: object
  config:
    fields:
      id: { type: "ID!" }
      name: { type: "String!" }
      children: { type: "[Category]", resolve: "@App\\GraphQL\\Category\\CategoryResolver::children" }
Query:
  type: object
  config:
    fields:
      categories:
        type: "[Category]"
        resolve: "@App\\GraphQL\\Category\\CategoryQuery"
