tests:
  type: object
  config:
    fields:
      id: { type: "ID!" }
      name: { type: "String!" }
      children: { type: "[tests]", resolve: "@App\\GraphQL\\tests\\testsResolver::children" }
Query:
  type: object
  config:
    fields:
      categories:
        type: "[tests]"
        resolve: "@App\\GraphQL\\tests\\testsQuery"
