$paths = @(
    'src/Domain/tests/Acl/AclPolicyService.php'
    'src/Domain/tests/Acl/AclRepositoryInterface.php'
    'src/Domain/tests/ApproxTotalService.php'
    'src/Domain/tests/tests.php'
    'src/Domain/tests/testsInterface.php'
    'src/Domain/tests/testsRepositoryInterface.php'
    'src/Domain/tests/testsService.php'
    'src/Domain/tests/CollectionImportService.php'
    'src/Domain/tests/CollectionService.php'
    'src/Domain/tests/Graphql/testsLoader.php'
    'src/Domain/tests/Graphql/GraphqlGuard.php'
    'src/Domain/tests/Import/ImportRepositoryInterface.php'
    'src/Domain/tests/Import/ImportService.php'
    'src/Domain/tests/Quota/CacheStoreInterface.php'
    'src/Domain/tests/Quota/QuotaService.php'
    'src/Domain/tests/Quota/TokenBucket.php'
    'src/Domain/tests/Rule/RuleAdminService.php'
    'src/Domain/tests/Rule/RuleEngine.php'
    'src/Domain/tests/Rule/RuleRepositoryInterface.php'
    'src/Domain/tests/Seo/SeoRepositoryInterface.php'
    'src/Domain/tests/Suggest/RuleSuggestService.php'
    'src/DomainInterface/tests/testsServiceInterface.php'
    'src/DomainInterface/tests/CollectionImportServiceInterface.php'
    'src/DomainInterface/tests/CollectionServiceInterface.php'
    'src/Infra/tests/CacheInvalidator.php'
    'src/Infra/tests/testsAuditLogger.php'
    'src/Infra/tests/HttpWebhookSender.php'
    'src/Infra/tests/MessengerOutboxDispatcher.php'
    'src/Infra/tests/OrderWebhookPublisher.php'
    'src/Infra/tests/ProductWebhookPublisher.php'
    'src/InfraInterface/tests/OutboxDispatcherInterface.php'
    'src/InfraInterface/tests/WebhookSenderInterface.php'
    'src/Adapter/tests/StorefrontAdapter.php'
    'src/Http/tests/WebhookController.php'
    'src/Http/tests/SecurityHeaderListener.php'
    'src/Domain'
    'src/DomainInterface'
    'src/Infra'
    'src/InfraInterface'
    'src/Adapter'
    'src/Http'
)

foreach ($rel in $paths) {
    $full = Join-Path $PSScriptRoot ('..\' + $rel.Replace('/', '\'))
    if (Test-Path $full) {
        Remove-Item $full -Recurse -Force
    }
}
